name: Build Vue and publish on GH

on: [push]

jobs:
  build_vue:
    runs-on: ubuntu-latest
    name: Build Vue
    steps:
    - uses: actions/checkout@v2
    - id: Build-Vue
      uses: xRealNeon/VuePagesAction@1.0.1
      with:
        # TODO: make it dynamic from env
        username: 'esnvutbrno'
        reponame: 'link-list'
        cname: links.esnvutbrno.cz
        useyarn: true
        token: ${{ secrets.GITHUB_TOKEN }} # Leave this line unchanged
